Repository FACG6/zajel, pull requests merged in 2019-06, with the labels that each got.

#121 Fix header
  client/src/App.jsx
  client/src/Components/CommonComponent/Header/index.jsx
  client/src/Components/CommonComponent/Header/style.css
  client/src/Components/CommonComponent/Navbar/index.jsx
  client/src/Components/CommonComponent/Navbar/style.css
  client/src/Components/CommonComponent/Sidebar/index.jsx
  client/src/Components/CommonComponent/Sidebar/style.css
  client/src/Components/Layouts/Customers/index.jsx
  client/src/index.css
Labels: approve

#127 Login route backend
  server/controller/accountsMangment/admin/checkLogin.js
  server/controller/accountsMangment/admin/index.js
  server/controller/index.js
  server/controller/middleware/authentication.js
  server/controller/middleware/protectRoute.js
  server/database/queries/admin/checkAdmin.js
Labels: awaiting review

#135 Customer deatils backend route
  server/controller/accountsMangment/customer/getCustomerDetails.js
  server/controller/accountsMangment/customer/index.js
  server/controller/index.js
  server/database/config/dbBuild.sql
  server/database/config/dbFake.sql
  server/database/config/fakeData.sql
  server/database/queries/customer/getCustomerDetails.js
Labels: awaiting review

#131 pass the popup html to the table and add margin to the dropdown of t…
  client/src/Components/CommonComponent/Header/style.css
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/CommonComponent/Table/style.css
Labels: approve

#136 Delete order backend
  server/controller/index.js
  server/controller/order/deleteOrder.js
  server/controller/order/index.js
  server/database/config/dbBuild.sql
  server/database/queries/order/deleteOrder.js
Labels: awaiting review

#137 Home page backend
  client/src/App.jsx
  client/src/Components/CommonComponent/CountBox/style.css
  client/src/Components/Layouts/Home/index.jsx
  client/src/Components/Layouts/Home/style.css
  server/controller/getCounts.js
  server/controller/index.js
  server/controller/middleware/authentication.js
  server/database/queries/captain/getCaptainsCount.js
  server/database/queries/customer/getCustomersCount.js
  server/database/queries/order/getOrdersCount.js
Labels: awaiting review

#141 customer page -back end
  server/controller/accountsMangment/customer/getCustomers.js
  server/controller/accountsMangment/customer/index.js
  server/database/config/dbBulid.sql
  server/database/queries/customer/getCustomers.js
Labels: awaiting review

#134 Customer page front end
  client/src/App.jsx
  client/src/Components/CommonComponent/Button/style.css
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/CommonComponent/Table/style.css
  client/src/Components/Layouts/Customers/index.jsx
  client/src/Components/Layouts/Customers/style.css
  server/controller/accountsMangment/customer/getCustomers.js
  server/controller/index.js
Labels: awaiting review

#139 Get image backend
  server/controller/getImage.js
  server/controller/index.js
  server/upload/test.png
Labels: awaiting review

#144 Captain details backend
  server/controller/accountsMangment/captains/getCaptainDetails.js
  server/controller/accountsMangment/captains/index.js
  server/controller/index.js
  server/database/queries/captain/getCaptainDetails.js
Labels: awaiting review

#132 Customer profile route
  client/src/App.jsx
  client/src/Components/CommonComponent/Header/index.jsx
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/Layouts/Login/index.jsx
  client/src/Components/Layouts/SingleCustomer/Popups/Popup.jsx
  client/src/Components/Layouts/SingleCustomer/Popups/deletePopup.jsx
  client/src/Components/Layouts/SingleCustomer/index.jsx
  client/src/Components/Layouts/SingleCustomer/style.css
  server/controller/accountsMangment/admin/checkLogin.js
  server/controller/accountsMangment/customer/getCustomerOrders.js
  server/controller/accountsMangment/customer/index.js
  server/database/config/dbBulid.sql
  server/database/config/dbFake.sql
  server/database/queries/customer/getCustomerOrders.js
  server/database/queries/order/getOrderDetails.js
Labels: awaiting review

#152 Fix dropdown menu
  client/src/Components/CommonComponent/Table/dropdownMenu.jsx
Labels: approve

#154 Add captain/front and back
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/Layouts/Captains/Popups/AddCaptain.jsx
  client/src/Components/Layouts/Captains/index.jsx
  client/src/Components/Layouts/Captains/style.css
  server/controller/accountsMangment/captains/addCaptain.js
  server/controller/accountsMangment/captains/index.js
  server/controller/index.js
  server/database/config/dbBulid.sql
  server/database/queries/captain/addCaptain.js
  server/upload/user.png
Labels: awaiting review, in-progress

#161 Fix style popup add captain
  client/src/Components/Layouts/Captains/Popups/AddCaptain.jsx
  client/src/Components/Layouts/Captains/style.css
Labels: awaiting review

#159 Add customer popup front end
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/CommonComponent/Button/style.css
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/CommonComponent/Table/style.css
  client/src/Components/Layouts/Customers/addcustomer.jsx
  client/src/Components/Layouts/Customers/index.jsx
  client/src/Components/Layouts/Customers/style.css
  client/src/Components/Layouts/SingleCustomer/Popups/deletePopup.jsx
  server/controller/accountsMangment/customer/addCustomer.js
  server/controller/accountsMangment/customer/index.js
  server/controller/index.js
  server/database/queries/customer/addCustomer.js
  server/database/queries/customer/checkCustomer.js
Labels: Front End, request change

#164 View order customer
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/Layouts/SingleCustomer/Popups/viewPopUp.jsx
  client/src/Components/Layouts/SingleCustomer/index.jsx
  client/src/Components/Layouts/SingleCustomer/style.css
  server/database/queries/order/getOrderDetails.js
Labels: awaiting review

#166 Get places names
  server/controller/index.js
  server/controller/place/getPlacesNames.js
  server/controller/place/index.js
  server/database/queries/place/getPlaceName.js
Labels: awaiting review

#165 Get captain name
  server/controller/accountsMangment/captains/getCaptaisnNames.js
  server/controller/accountsMangment/captains/index.js
  server/controller/index.js
  server/database/queries/captain/getCaptainName.js
Labels: awaiting review

#169 handle delete customer
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/Layouts/Captains/Popups/AddCaptain.jsx
  client/src/Components/Layouts/Captains/style.css
  client/src/Components/Layouts/Customers/deletecustomer.jsx
  client/src/Components/Layouts/Customers/index.jsx
  client/src/Components/Layouts/Customers/style.css
  server/controller/accountsMangment/customer/deleteCustomer.js
  server/controller/accountsMangment/customer/index.js
  server/controller/index.js
  server/database/queries/customer/deleteCustomer.js
Labels: Back End, Front End, awaiting review

#170 Delete order front
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/Layouts/SingleCustomer/index.jsx
Labels: awaiting review

#115 Page/view captain
  client/src/App.jsx
  client/src/Components/CommonComponent/Header/style.css
  client/src/Components/CommonComponent/Table/Popups.jsx
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/Layouts/SingleCaptains/Popups/Popup.jsx
  client/src/Components/Layouts/SingleCaptains/Popups/deletePopup.jsx
  client/src/Components/Layouts/SingleCaptains/index.jsx
  client/src/Components/Layouts/SingleCaptains/style.css
  package-lock.json
  server/controller/accountsMangment/captains/getCaptainDetails.js
  server/controller/accountsMangment/captains/getCaptainOrders.js
  server/controller/accountsMangment/captains/index.js
  server/controller/index.js
Labels: awaiting review

#130 Add order component
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/CommonComponent/Table/Popups.jsx
  client/src/Components/Layouts/Login/index.jsx
  client/src/Components/Layouts/Order/addOrder.jsx
  client/src/Components/Layouts/Order/index.jsx
  client/src/Components/Layouts/Order/style.css
  package-lock.json
  package.json
  server/controller/index.js
  server/controller/order/index.js
  server/controller/order/postOrder.js
  server/database/config/dbBulid.sql
  server/database/queries/captain/insertTuserOrder.js
  server/database/queries/item/insertItem.js
Labels: awaiting review

#176 Page not found
  client/package-lock.json
  client/src/App.jsx
  client/src/Components/Layouts/NotFound/index.jsx
  client/src/Components/Layouts/NotFound/style.css
Labels: Front End, awaiting review

#171 Add order backend
  client/src/Components/Layouts/Order/addOrder.jsx
  server/controller/order/index.js
  server/controller/order/postOrder.js
  server/database/queries/captain/insertTuserOrder.js
  server/database/queries/item/insertItem.js
  server/database/queries/order/addOrder.js
Labels: awaiting review

#177 On progress
  client/src/Components/Layouts/ToBuildLater/index.jsx
  client/src/Components/Layouts/ToBuildLater/style.css
Labels: Front End, awaiting review

#173 api of all routes front end
  client/package-lock.json
  client/src/App.jsx
  client/src/Components/CommonComponent/Navbar/index.jsx
  client/src/Components/CommonComponent/Navbar/style.css
  client/src/Components/CommonComponent/Sidebar/index.jsx
  client/src/Components/HOC/WithNavSide.jsx
  client/src/Components/HOC/privte.js
  client/src/Components/HOC/public.js 
  client/src/Components/Layouts/Captains/index.jsx
  client/src/Components/Layouts/Customers/index.jsx
  client/src/Components/Layouts/Home/index.jsx
  client/src/Components/Layouts/NotFound/index.jsx
  client/src/Components/Layouts/Ordersmanagement/index.jsx
  client/src/Components/Layouts/SingleCaptains/index.jsx
  client/src/Components/Layouts/SingleCustomer/index.jsx
  client/src/Components/Layouts/ToBuildLater/index.jsx
  client/src/Components/Layouts/ToBuildLater/style.css
  server/controller/accountsMangment/admin/getName.js
  server/controller/accountsMangment/admin/index.js
  server/controller/accountsMangment/admin/logout.js
  server/controller/index.js
Labels: awaiting review

#178 Captain managment
  client/src/App.jsx
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/Layouts/Captains/index.jsx
  client/src/Components/Layouts/Captains/style.css
  client/src/Components/Layouts/SingleCaptains/index.jsx
  package-lock.json
  server/controller/accountsMangment/captains/getCaptains.js
  server/controller/accountsMangment/captains/index.js
  server/database/queries/captain/getCaptains.js
Labels: awaiting review

#174 Edit customer front/back
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/Layouts/Customers/addcustomer.jsx
  client/src/Components/Layouts/Customers/deletecustomer.jsx
  client/src/Components/Layouts/Customers/editcustomer.jsx
  client/src/Components/Layouts/Customers/index.jsx
  client/src/Components/Layouts/Customers/style.css
  server/controller/accountsMangment/customer/editCustomer.js
  server/controller/accountsMangment/customer/index.js
  server/database/queries/customer/checkCustomerId.js
  server/database/queries/customer/editCustomer.js
Labels: awaiting review

#182 Modify backend image captain
  server/controller/getImage.js
  server/database/config/dbFake.sql
  server/database/queries/captain/getCaptainName.js
Labels: awaiting review

#157 Edit captain/front back
  client/package-lock.json
  client/src/App.jsx
  client/src/Components/Layouts/Captains/EditCaptain/editCaptain.jsx
  client/src/Components/Layouts/Captains/EditCaptain/index.jsx
  client/src/Components/Layouts/Captains/EditCaptain/style.css
  client/src/Components/Layouts/SingleCustomer/index.jsx
  package-lock.json
  package.json
  server/controller/accountsMangment/captains/editCaptain.js
  server/controller/accountsMangment/captains/index.js
  server/controller/index.js
  server/database/config/dbConnection.js
  server/database/queries/captain/editCaptain.js
  server/database/queries/captain/isCaptain.js
Labels: awaiting review

#155 Orders management
  client/src/App.css
  client/src/App.jsx
  client/src/Components/CommonComponent/Header/index.jsx
  client/src/Components/CommonComponent/Header/style.css
  client/src/Components/CommonComponent/Navbar/index.jsx
  client/src/Components/CommonComponent/Navbar/style.css
  client/src/Components/CommonComponent/Table/Popups.jsx
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/CommonComponent/Table/style.css
  client/src/Components/Layouts/Customers/style.css
  client/src/Components/Layouts/Order/addOrder.jsx
  client/src/Components/Layouts/Order/style.css
  client/src/Components/Layouts/Ordersmanagement/OrdersFilter.jsx
  client/src/Components/Layouts/Ordersmanagement/index.jsx
  client/src/Components/Layouts/Ordersmanagement/style.css
  client/src/Components/Layouts/SingleCaptains/index.jsx
  client/src/index.css
  server/controller/index.js
  server/controller/order/getOrders.js
  server/controller/order/index.js
  server/controller/order/updateOrder.js
  server/controller/stores/index.js
  server/database/config/fakeData.sql
  server/database/queries/item/checkItem.js
  server/database/queries/item/deleteItem.js
  server/database/queries/item/editItem.js
  server/database/queries/item/insertItem.js
  server/database/queries/order/editOrder.js
  server/database/queries/order/getOrders.js
  server/database/queries/place/getStores.js
Labels: in-progress

#191 View order fexed style
  client/src/Components/Layouts/Order/style.css
  client/src/Components/Layouts/SingleCaptains/Popups/viewPopUp.jsx
  client/src/Components/Layouts/SingleCaptains/style.css
  client/src/Components/Layouts/SingleCustomer/Popups/viewPopUp.jsx
Labels: awaiting review

#193 Fix style view captian
  client/src/Components/CommonComponent/Table/Popups.jsx
  client/src/Components/CommonComponent/Table/Table.jsx
Labels: awaiting review

#196 make valadation for addOrder
  client/package-lock.json
  package-lock.json
  server/controller/order/postOrder.js
  server/controller/utils/addOrderValadation.js
Labels: Back End, awaiting review

#198 Fix bug
  client/src/App.jsx
  client/src/Components/Layouts/Captains/Popups/AddCaptain.jsx
  client/src/Components/Layouts/Captains/index.jsx
  client/src/Components/Layouts/SingleCaptains/index.jsx
  client/src/Components/Layouts/SingleCustomer/index.jsx
  client/src/Components/Layouts/SingleCustomer/style.css
  server/controller/accountsMangment/captains/getCaptainDetails.js
  server/controller/accountsMangment/customer/getCustomerDetails.js
Labels: awaiting review

#212 Title website
  client/public/favicon.ico
  client/public/index.html
  client/src/Components/Layouts/Order/addOrder.jsx
Labels: awaiting review

#219 Fix single tuser
  client/src/Components/Layouts/SingleCaptains/Popups/viewPopUp.jsx
  client/src/Components/Layouts/SingleCustomer/Popups/viewPopUp.jsx
  server/controller/accountsMangment/captains/getCaptainOrders.js
  server/controller/accountsMangment/customer/getCustomerOrders.js
  server/database/queries/order/getOrderDetails.js
Labels: awaiting review

#221 Database fake data
  .travis.yml
  server/controller/accountsMangment/captains/editCaptain.js
  server/controller/utils/editCaptainSchema.js
  server/database/config/dbBulid.sql
  server/database/config/dbFake.sql
Labels: awaiting review

#207 edit captain front end validation schema
  server/controller/accountsMangment/captains/editCaptain.js
  server/controller/utils/editCaptainSchema.js
Labels: awaiting review
