Repository FACG6/zajel, pull requests merged in 2019-05, with the labels that each got.

#96 Setupt
  .eslintrc.json
  .gitignore
  .travis.yml
  ReactAppREADME.md
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/serviceWorker.js
  package-lock.json
  package.json
  server/app.js
  server/controller/index.js
  server/index.js
  src/App.css
  src/App.js
  src/logo.svg
Labels: approve

#101 main components styling
  client/package-lock.json
  client/src/index.css
  package-lock.json
Labels: approve

#104 Count box
  client/package-lock.json
  client/package.json
  client/src/Components/CommonComponent/CountBox/index.jsx
  client/src/Components/CommonComponent/CountBox/style.css
Labels: approve

#103 headerComponent
  client/src/Components/CommonComponent/Header/index.jsx
  client/src/Components/CommonComponent/Header/style.css
Labels: approve

#107 Page/login
  client/package-lock.json
  client/package.json
  client/src/Components/Layouts/Login/index.jsx
  client/src/Components/Layouts/Login/style.css
Labels: approve

#111 Deploy
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
Labels: approve

#119 Middleware
  server/controller/index.js
  server/controller/middleware/authentication.js
  server/controller/middleware/authorization.js
  server/controller/middleware/protectRoute.js
Labels: awaiting review

#110 Home page
  client/package-lock.json
  client/src/App.jsx
  client/src/Components/CommonComponent/CountBox/index.jsx
  client/src/Components/CommonComponent/CountBox/style.css
  client/src/Components/CommonComponent/Header/index.jsx
  client/src/Components/CommonComponent/Header/style.css
  client/src/Components/Layouts/Home/index.jsx
  client/src/Components/Layouts/Home/style.css
Labels: awaiting review

#113 Side bar
  client/package-lock.json
  client/src/App.jsx
  client/src/Components/CommonComponent/Sidebar/index.jsx
  client/src/Components/CommonComponent/Sidebar/style.css
  client/src/index.css
Labels: awaiting review

#120 Fix database
  server/database/config/dbBuild.sql
  server/database/config/dbFake.sql
Labels: awaiting review

#114 Table
  client/.eslintrc.json
  client/src/App.jsx
  client/src/Components/CommonComponent/Table/Popups.jsx
  client/src/Components/CommonComponent/Table/Table.jsx
  client/src/Components/CommonComponent/Table/dropdownMenu.jsx
  client/src/Components/CommonComponent/Table/index.jsx
  client/src/Components/CommonComponent/Table/style.css
  client/src/Components/CommonComponent/table/style.css
  client/src/Components/Layouts/Ordersmanagement/OrdersFilter.jsx
  client/src/Components/Layouts/Ordersmanagement/index.jsx
Labels: request change
